services:
  ingestion-service:
    container_name: ingestion-service
    build:
      context: .
      dockerfile: ./ingestion-service/Dockerfile
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
  zookeeper:
    extends:
      file: ./kafka/docker-compose.yml
      service: zookeeper
  kafka:
    extends:
      file: ./kafka/docker-compose.yml
      service: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
