apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  type: NodePort
  selector:
    app: ingestion-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
