apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
      - name: ingestion-container
        image: ingestion-service:local
        imagePullPolicy: Never          
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
