.PHONY: dev run

# ================================
#          Go Commands
# ================================

dev:
	@echo "Running with live reload..."
	ENV=LOCAL air

run:
	ENV=LOCAL go run ./cmd/main